In [1]:
import pandas as pd

df = pd.read_csv(
    "opi_builder_c_live_record.csv"
)

print(df.shape)

print()

print(df["Label"].value_counts())

(7013, 12)

Label
NORMAL    6436
ATTACK     577
Name: count, dtype: int64

In [2]:
eda = df.groupby("Label").agg({

    "Flow Duration":"median",

    "Flow Bytes/s":"median",

    "Flow Packets/s":"median",

    "Total Fwd Packets":"median",

    "Total Length of Fwd Packets":"median",

    "Fwd Packets/s":"median",

    "SYN Flag Count":"median",

    "ACK Flag Count":"median",

    "Init_Win_bytes_forward":"median",

    "act_data_pkt_fwd":"median"

})

eda

,Flow Duration,Flow Bytes/s,Flow Packets/s,Total Fwd Packets,Total Length of Fwd Packets,Fwd Packets/s,SYN Flag Count,ACK Flag Count,Init_Win_bytes_forward,act_data_pkt_fwd
Label,,,,,,,,,,
ATTACK,4.975630,4157.860454,69.297674,336.0,20160.0,69.297674,336.0,0.0,512.0,336.0
NORMAL,0.659181,15437.015455,20.946547,11.0,7784.0,20.946547,0.0,11.0,510.0,9.0

In [3]:
features = [

    "Flow Duration",

    "Flow Bytes/s",

    "Flow Packets/s",

    "Total Fwd Packets",

    "Total Length of Fwd Packets",

    "Fwd Packets/s",

    "SYN Flag Count",

    "ACK Flag Count",

    "Init_Win_bytes_forward",

    "act_data_pkt_fwd"

]

result = []

for col in features:

    attack_median = eda.loc["ATTACK", col]

    normal_median = eda.loc["NORMAL", col]

    ratio = (

        attack_median /
        normal_median

        if normal_median != 0

        else 999999

    )

    result.append([

        col,

        attack_median,

        normal_median,

        ratio

    ])

result_df = pd.DataFrame(

    result,

    columns=[

        "Feature",

        "Attack_Median",

        "Normal_Median",

        "Ratio"

    ]

)

result_df = result_df.sort_values(

    by="Ratio",

    ascending=False

)

result_df

                       Feature  Attack_Median  Normal_Median          Ratio
6               SYN Flag Count     336.000000       0.000000  999999.000000
9             act_data_pkt_fwd     336.000000       9.000000      37.333333
3            Total Fwd Packets     336.000000      11.000000      30.545455
0                Flow Duration       4.975630       0.659181       7.548197
2               Flow Packets/s      69.297674      20.946547       3.308310
5                Fwd Packets/s      69.297674      20.946547       3.308310
4  Total Length of Fwd Packets   20160.000000    7784.000000       2.589928
8       Init_Win_bytes_forward     512.000000     510.000000       1.003922
1                 Flow Bytes/s    4157.860454   15437.015455       0.269344
7               ACK Flag Count       0.000000      11.000000       0.000000