In [1]:
# =============================================================================
# LOAD DATASET
# =============================================================================

import pandas as pd
import numpy as np

cic = pd.read_csv(
    r"I:\TA\syn\syn_clean.csv"
)

lab = pd.read_csv(
    r"I:\TA\syn\syn_lab_balanced.csv"
)

print("CIC :", cic.shape)
print("LAB :", lab.shape)

CIC : (62028, 82)
LAB : (30706, 12)

In [2]:
# =============================================================================
# FEATURE LIST
# =============================================================================

FEATURES = [

    "Flow Duration",
    "Flow Bytes/s",
    "Flow Packets/s",
    "Total Fwd Packets",
    "Total Length of Fwd Packets",
    "Fwd Packets/s",
    "SYN Flag Count",
    "ACK Flag Count",
    "Init_Win_bytes_forward",
    "act_data_pkt_fwd"

]

In [3]:
# =============================================================================
# CIC STATS
# =============================================================================

print("="*80)
print("CIC DATASET")
print("="*80)

cic_stats = cic[FEATURES].describe().T

display(cic_stats)

================================================================================
CIC DATASET
================================================================================

,count,mean,std,min,25%,50%,75%,max
Flow Duration,62028.0,1.021218e+07,2.845162e+07,1.000000,2.000000,108.000,41212.5,1.199929e+08
Flow Bytes/s,62028.0,6.044942e+06,3.833931e+07,0.000000,3619.300875,216216.220,9000000.0,1.734000e+09
Flow Packets/s,62028.0,5.683088e+05,8.525849e+05,0.035716,118.895207,36363.637,1000000.0,3.000000e+06
Total Fwd Packets,62028.0,6.460824e+00,3.523137e+01,1.000000,2.000000,2.000,2.0,4.648000e+03
Total Length of Fwd Packets,62028.0,4.524034e+02,2.883231e+03,0.000000,12.000000,12.000,70.0,2.085240e+05
Fwd Packets/s,62028.0,5.597037e+05,8.530011e+05,0.033990,47.226057,18181.818,1000000.0,3.000000e+06
SYN Flag Count,62028.0,2.450506e-03,4.944230e-02,0.000000,0.000000,0.000,0.0,1.000000e+00
ACK Flag Count,62028.0,6.026794e-01,4.893473e-01,0.000000,0.000000,1.000,1.0,1.000000e+00
Init_Win_bytes_forward,62028.0,5.695028e+03,7.571754e+03,-1.000000,255.000000,5840.000,5840.0,6.553500e+04
act_data_pkt_fwd,62028.0,3.768250e+00,2.407038e+01,0.000000,1.000000,1.000,1.0,3.888000e+03

In [4]:
# =============================================================================
# LAB STATS
# =============================================================================

print("="*80)
print("LAB DATASET")
print("="*80)

lab_stats = lab[FEATURES].describe().T

display(lab_stats)

================================================================================
LAB DATASET
================================================================================

,count,mean,std,min,25%,50%,75%,max
Flow Duration,30706.0,46.265614,1.874731e+02,0.000001,0.196370,32.747877,45.782072,5.084128e+03
Flow Bytes/s,30706.0,90123.730239,1.246237e+06,1.599312,14.073477,57.766127,52584.105926,7.400000e+07
Flow Packets/s,30706.0,587.699060,1.899321e+04,0.006070,0.232840,0.949253,104.124523,1.000000e+06
Total Fwd Packets,30706.0,65.317462,5.998181e+02,1.000000,10.000000,13.000000,50.000000,4.009800e+04
Total Length of Fwd Packets,30706.0,49546.967531,1.247573e+06,54.000000,600.000000,3120.000000,7921.000000,1.391935e+08
Fwd Packets/s,30706.0,587.699060,1.899321e+04,0.006070,0.232840,0.949253,104.124523,1.000000e+06
SYN Flag Count,30706.0,11.159806,1.683505e+01,0.000000,1.000000,4.000000,10.000000,5.200000e+01
ACK Flag Count,30706.0,54.411678,6.004822e+02,0.000000,0.000000,0.000000,17.000000,4.009600e+04
Init_Win_bytes_forward,30706.0,32295.701817,3.222235e+04,0.000000,512.000000,512.000000,65535.000000,6.553500e+04
act_data_pkt_fwd,30706.0,39.433889,4.222327e+02,0.000000,8.000000,8.000000,11.000000,3.430500e+04

In [5]:
# =============================================================================
# COMPARE TABLE
# =============================================================================

rows = []

for col in FEATURES:

    rows.append({

        "Feature": col,

        "CIC Mean":
            cic[col].mean(),

        "LAB Mean":
            lab[col].mean(),

        "CIC Median":
            cic[col].median(),

        "LAB Median":
            lab[col].median(),

        "CIC Max":
            cic[col].max(),

        "LAB Max":
            lab[col].max()

    })

compare_df = pd.DataFrame(rows)

compare_df

,Feature,CIC Mean,LAB Mean,CIC Median,LAB Median,CIC Max,LAB Max
0,Flow Duration,1.021218e+07,46.265614,108.000,32.747877,1.199929e+08,5.084128e+03
1,Flow Bytes/s,6.044942e+06,90123.730239,216216.220,57.766127,1.734000e+09,7.400000e+07
2,Flow Packets/s,5.683088e+05,587.699060,36363.637,0.949253,3.000000e+06,1.000000e+06
3,Total Fwd Packets,6.460824e+00,65.317462,2.000,13.000000,4.648000e+03,4.009800e+04
4,Total Length of Fwd Packets,4.524034e+02,49546.967531,12.000,3120.000000,2.085240e+05,1.391935e+08
5,Fwd Packets/s,5.597037e+05,587.699060,18181.818,0.949253,3.000000e+06,1.000000e+06
6,SYN Flag Count,2.450506e-03,11.159806,0.000,4.000000,1.000000e+00,5.200000e+01
7,ACK Flag Count,6.026794e-01,54.411678,1.000,0.000000,1.000000e+00,4.009600e+04
8,Init_Win_bytes_forward,5.695028e+03,32295.701817,5840.000,512.000000,6.553500e+04,6.553500e+04
9,act_data_pkt_fwd,3.768250e+00,39.433889,1.000,8.000000,3.888000e+03,3.430500e+04

In [6]:
# =============================================================================
# LABEL DISTRIBUTION
# =============================================================================

print("CIC")

print(
    cic["Label"]
    .value_counts()
)

print()

print("LAB")

print(
    lab["Label"]
    .value_counts()
)

CIC
Label
1    31014
0    31014
Name: count, dtype: int64

LAB
Label
0    15354
1    15352
Name: count, dtype: int64

In [7]:
# =============================================================================
# FEATURE RANGE CHECK
# =============================================================================

for col in FEATURES:

    print()
    print("="*80)
    print(col)
    print("="*80)

    print("CIC")

    print(
        cic[col]
        .describe()
    )

    print()

    print("LAB")

    print(
        lab[col]
        .describe()
    )

================================================================================
Flow Duration
================================================================================
CIC
count    6.202800e+04
mean     1.021218e+07
std      2.845162e+07
min      1.000000e+00
25%      2.000000e+00
50%      1.080000e+02
75%      4.121250e+04
max      1.199929e+08
Name: Flow Duration, dtype: float64

LAB
count    30706.000000
mean        46.265614
std        187.473053
min          0.000001
25%          0.196370
50%         32.747877
75%         45.782072
max       5084.127719
Name: Flow Duration, dtype: float64

================================================================================
Flow Bytes/s
================================================================================
CIC
count    6.202800e+04
mean     6.044942e+06
std      3.833931e+07
min      0.000000e+00
25%      3.619301e+03
50%      2.162162e+05
75%      9.000000e+06
max      1.734000e+09
Name: Flow Bytes/s, dtype: float64

LAB
count    3.070600e+04
mean     9.012373e+04
std      1.246237e+06
min      1.599312e+00
25%      1.407348e+01
50%      5.776613e+01
75%      5.258411e+04
max      7.400000e+07
Name: Flow Bytes/s, dtype: float64

================================================================================
Flow Packets/s
================================================================================
CIC
count    6.202800e+04
mean     5.683088e+05
std      8.525849e+05
min      3.571637e-02
25%      1.188952e+02
50%      3.636364e+04
75%      1.000000e+06
max      3.000000e+06
Name: Flow Packets/s, dtype: float64

LAB
count      30706.000000
mean         587.699060
std        18993.205360
min            0.006070
25%            0.232840
50%            0.949253
75%          104.124523
max      1000000.000000
Name: Flow Packets/s, dtype: float64

================================================================================
Total Fwd Packets
================================================================================
CIC
count    62028.000000
mean         6.460824
std         35.231370
min          1.000000
25%          2.000000
50%          2.000000
75%          2.000000
max       4648.000000
Name: Total Fwd Packets, dtype: float64

LAB
count    30706.000000
mean        65.317462
std        599.818121
min          1.000000
25%         10.000000
50%         13.000000
75%         50.000000
max      40098.000000
Name: Total Fwd Packets, dtype: float64

================================================================================
Total Length of Fwd Packets
================================================================================
CIC
count     62028.000000
mean        452.403350
std        2883.231396
min           0.000000
25%          12.000000
50%          12.000000
75%          70.000000
max      208524.000000
Name: Total Length of Fwd Packets, dtype: float64

LAB
count    3.070600e+04
mean     4.954697e+04
std      1.247573e+06
min      5.400000e+01
25%      6.000000e+02
50%      3.120000e+03
75%      7.921000e+03
max      1.391935e+08
Name: Total Length of Fwd Packets, dtype: float64

================================================================================
Fwd Packets/s
================================================================================
CIC
count    6.202800e+04
mean     5.597037e+05
std      8.530011e+05
min      3.399032e-02
25%      4.722606e+01
50%      1.818182e+04
75%      1.000000e+06
max      3.000000e+06
Name: Fwd Packets/s, dtype: float64

LAB
count      30706.000000
mean         587.699060
std        18993.205360
min            0.006070
25%            0.232840
50%            0.949253
75%          104.124523
max      1000000.000000
Name: Fwd Packets/s, dtype: float64

================================================================================
SYN Flag Count
================================================================================
CIC
count    62028.000000
mean         0.002451
std          0.049442
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: SYN Flag Count, dtype: float64

LAB
count    30706.000000
mean        11.159806
std         16.835049
min          0.000000
25%          1.000000
50%          4.000000
75%         10.000000
max         52.000000
Name: SYN Flag Count, dtype: float64

================================================================================
ACK Flag Count
================================================================================
CIC
count    62028.000000
mean         0.602679
std          0.489347
min          0.000000
25%          0.000000
50%          1.000000
75%          1.000000
max          1.000000
Name: ACK Flag Count, dtype: float64

LAB
count    30706.000000
mean        54.411678
std        600.482179
min          0.000000
25%          0.000000
50%          0.000000
75%         17.000000
max      40096.000000
Name: ACK Flag Count, dtype: float64

================================================================================
Init_Win_bytes_forward
================================================================================
CIC
count    62028.000000
mean      5695.027729
std       7571.753832
min         -1.000000
25%        255.000000
50%       5840.000000
75%       5840.000000
max      65535.000000
Name: Init_Win_bytes_forward, dtype: float64

LAB
count    30706.000000
mean     32295.701817
std      32222.346682
min          0.000000
25%        512.000000
50%        512.000000
75%      65535.000000
max      65535.000000
Name: Init_Win_bytes_forward, dtype: float64

================================================================================
act_data_pkt_fwd
================================================================================
CIC
count    62028.000000
mean         3.768250
std         24.070378
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max       3888.000000
Name: act_data_pkt_fwd, dtype: float64

LAB
count    30706.000000
mean        39.433889
std        422.232748
min          0.000000
25%          8.000000
50%          8.000000
75%         11.000000
max      34305.000000
Name: act_data_pkt_fwd, dtype: float64