In [1]:
import pandas as pd

df = pd.read_csv("dataset_unbalanced_final.csv")

print(df["Label"].value_counts())

Label
NORMAL    6436
ATTACK    5305
Name: count, dtype: int64

In [2]:
from imblearn.under_sampling import RandomUnderSampler

X = df.drop("Label", axis=1)
y = df["Label"]

rus = RandomUnderSampler(
    sampling_strategy="auto",
    random_state=42
)

X_balanced, y_balanced = rus.fit_resample(X, y)

In [3]:
balanced_df = pd.concat(
    [
        X_balanced,
        y_balanced
    ],
    axis=1
)

balanced_df.head()

,Flow Duration,Flow Bytes/s,Flow Packets/s,Total Fwd Packets,SYN Flag Count,ACK Flag Count,Init_Win_bytes_forward,Label
0,3.361133,176.726129,2.677669,9,0,9,53248,ATTACK
8,0.343911,790.903001,11.630926,4,1,4,65535,ATTACK
10,4.216026,1269.916390,11.147940,47,0,47,615,ATTACK
11,4.997871,1752.146175,28.011929,140,127,13,512,ATTACK
12,2.449784,342.887401,5.306591,13,0,11,53248,ATTACK

In [4]:
balanced_df = balanced_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

In [5]:
balanced_df.to_csv(
    "dataset_balanced_final.csv",
    index=False
)

In [6]:
print("="*50)
print("BALANCED DATASET")
print("="*50)

print()

print(balanced_df["Label"].value_counts())

print()

print(
    balanced_df["Label"].value_counts(normalize=True)
)

==================================================
BALANCED DATASET
==================================================

Label
ATTACK    5305
NORMAL    5305
Name: count, dtype: int64

Label
ATTACK    0.5
NORMAL    0.5
Name: proportion, dtype: float64

In [7]:
print("="*50)
print("MISSING VALUE")
print("="*50)

print()

print(
    balanced_df.isnull().sum()
)

==================================================
MISSING VALUE
==================================================

Flow Duration             0
Flow Bytes/s              0
Flow Packets/s            0
Total Fwd Packets         0
SYN Flag Count            0
ACK Flag Count            0
Init_Win_bytes_forward    0
Label                     0
dtype: int64

In [8]:
print("="*50)
print("DUPLICATE")
print("="*50)

print()

print(
    balanced_df.duplicated().sum()
)

==================================================
DUPLICATE
==================================================

0

In [9]:
print("="*50)
print("DATA INFO")
print("="*50)

print()

balanced_df.info()

==================================================
DATA INFO
==================================================

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10610 entries, 0 to 10609
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Flow Duration           10610 non-null  float64
 1   Flow Bytes/s            10610 non-null  float64
 2   Flow Packets/s          10610 non-null  float64
 3   Total Fwd Packets       10610 non-null  int64
 4   SYN Flag Count          10610 non-null  int64
 5   ACK Flag Count          10610 non-null  int64
 6   Init_Win_bytes_forward  10610 non-null  int64
 7   Label                   10610 non-null  object
dtypes: float64(3), int64(4), object(1)
memory usage: 663.2+ KB

In [10]:
balanced_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Flow Duration,10610.0,2.641722,1.830350,0.005885,0.455371,3.060897,4.415584,4.998009e+00
Flow Bytes/s,10610.0,22245.097242,81187.437325,36.065168,247.498518,2137.787576,18004.321034,5.178161e+06
Flow Packets/s,10610.0,26.908142,49.726305,0.614685,3.287030,6.158817,30.846815,5.097805e+02
Total Fwd Packets,10610.0,32.478417,81.473089,3.000000,6.000000,11.000000,20.750000,7.830000e+02
SYN Flag Count,10610.0,9.573044,65.936824,0.000000,0.000000,0.000000,1.000000,7.830000e+02
ACK Flag Count,10610.0,23.314797,50.594789,0.000000,5.000000,11.000000,19.000000,6.960000e+02
Init_Win_bytes_forward,10610.0,33854.895099,29466.840552,0.000000,255.000000,53248.000000,65535.000000,6.553500e+04

In [11]:
print("="*60)
print("FINAL DATASET SUMMARY")
print("="*60)

print(f"Rows      : {len(balanced_df)}")
print(f"Columns   : {balanced_df.shape[1]}")
print(f"Features  : {balanced_df.shape[1]-1}")

print()

print("Class Distribution")

print(
    balanced_df["Label"].value_counts()
)

print()

print("Missing Value")

print(
    balanced_df.isnull().sum().sum()
)

print()

print("Duplicate")

print(
    balanced_df.duplicated().sum()
)

============================================================
FINAL DATASET SUMMARY
============================================================
Rows      : 10610
Columns   : 8
Features  : 7

Class Distribution
Label
ATTACK    5305
NORMAL    5305
Name: count, dtype: int64

Missing Value
0

Duplicate
0